version: '3'

services:
  client:
    build: 
      context: .
      dockerfile: ./docker/frontend/DockerfileVue
    command: npm run serve 
    volumes:
      - ./client:/client
    ports:
      - "8080:8080"

  server:
    build: 
      context: .
      dockerfile: ./docker/backend/DockerfileDjango
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - ./server:/server
    ports:
      - "7000:7000"
    depends_on:
      - db
      
  db:
    image: postgres
