# Generated by Django 2.1 on 2019-01-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultGameInLive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_array_living_cells', models.IntegerField()),
                ('iterations', models.IntegerField()),
                ('next_array_living_cells', models.IntegerField()),
                ('period_repetition_location', models.IntegerField()),
            ],
        ),
    ]
