# Generated by Django 2.1 on 2019-01-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_resultgameinlive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefeeditem',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
    ]
